name: Publish antonytm/mcp-sitecore-linux to Docker Hub
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push
        shell: bash
        run: |
          docker build -t antonytm/mcp-sitecore-linux:latest -t antonytm/mcp-sitecore-linux:0.20.0 -f ./docker/linux/Dockerfile .
          docker push antonytm/mcp-sitecore-linux:latest
          docker push antonytm/mcp-sitecore-linux:0.20.0