name: Publish antonytm/mcp-sitecore-windows to Docker Hub
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        shell: powershell
        run: |
          docker build --platform windows/amd64 -t antonytm/mcp-sitecore-windows:latest -t antonytm/mcp-sitecore-windows:0.20.1 -f ./docker/windows/Dockerfile .
          docker push antonytm/mcp-sitecore-windows:latest
          docker push antonytm/mcp-sitecore-windows:0.20.1
