name: Publish antonytm/mcp-sitecore-linux to Docker Hub
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: antonytm/mcp-sitecore-linux
          tags: 1.2.4-verbose-logging, latest
          registry: docker.io
          dockerfile: ./docker/linux/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}