name: Publish antonytm/mcp-sitecore-linux to Docker Hub
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        shell: bash
        run: |
          docker build -t antonytm/mcp-sitecore-linux:latest -t antonytm/mcp-sitecore-linux:0.20.1 -f ./docker/linux/Dockerfile .
          docker push antonytm/mcp-sitecore-linux:latest
          docker push antonytm/mcp-sitecore-linux:0.20.1